wrappers_settings:
  normalize_reward: true
  normalization_factor: 1.
  no_attack_buttons_combinations: false
  stack_frames: 4
  dilation: 1
  add_last_action: false
  stack_actions: 1
  scale: false
  exclude_image_scaling: true
  role_relative: false
  flatten: true
  filter_keys: [ "frame" ]

settings:
  shared:
    step_ratio: 6
    frame_shape: !!python/tuple [ 84, 84, 1 ]
    continue_game: 0.
    action_space: "discrete"
    outfits: !!python/tuple [ 1, 1 ]
    splash_screen: false

  sfiii3n:
    game_id: "sfiii3n"
    characters: !!python/tuple [ "Ryu", "Ken", "Makoto", "Hugo", "Urien" ]
    difficulty: 4
    super_art: !!python/tuple [ 1, 1 ]

  kof98umh:
    game_id: "kof98umh"
    characters: !!python/tuple [
      !!python/tuple [ "Kyo", "Benimaru", "Daimon" ],
      !!python/tuple [ "Iori", "Billy", "Chang" ],
      !!python/tuple [ "Chin", "Clark", "Mai" ],
    ]
    difficulty: 4
    fighting_style: !!python/tuple [ 1, 1 ]
    ultimate_style: !!python/tuple [
      !!python/tuple [ 1, 1, 1 ],
      !!python/tuple [ 1, 1, 1 ],
    ]

  umk3:
    game_id: "umk3"
    characters: !!python/tuple [ "Liu Kang", "Kitana", "Shang Tsung", "Nightwolf", "Jax" ]
    difficulty: 3

  samsh5sp:
    game_id: "samsh5sp"
    characters: !!python/tuple [ "Haohmaru", "Galford", "Nakoruru", "Tamtam", "Kusare" ]
    difficulty: 4