folders:
  parent_dir: "./transfer_agents/"
  model_name: "test_ppo_agent"

policy_kwargs:
  #net_arch: [{ pi: [64, 64], vf: [32, 32] }]
  #net_arch: [64, 64]

ppo_settings:
  policy_type: "MultiInputPolicy"
  gamma: 0.94
  model_checkpoint: "0"
  learning_rate: [2.5e-4, 2.5e-6] # To start
  clip_range: [0.15, 0.025] # To start
  batch_size: 1024 #8 #nminibatches gave different batch size depending on the number of environments: batch_size = (n_steps * n_envs) // nminibatches
  n_epochs: 4
  n_steps: 128
  autosave_freq: 250_000
  time_steps: 500_000
  n_train_epochs: 4
  n_eval_episodes: 5
  seeds: !!python/tuple [ 0 ]

  gae_lambda: 0.95
  ent_coef: 0.02
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  normalize_advantage: true # Whether to normalize or not the advantage
  stats_window_size: 100 # Window size for the rollout logging, specifying the number of episodes to average the reported success rate, mean episode length, and mean reward over
  target_kl: null
