folders:
  parent_dir: "./results/"
  model_name: "base_ppo_agent_samsho"

settings:
  game_id: "samsh5sp"
  step_ratio: 6
  frame_shape: !!python/tuple [84, 84, 1]
  continue_game: 0.0
  action_space: "multi_discrete"
  characters: "Haohmaru"
  difficulty: 5
  outfits: 1

env_settings:
  seed: 0
  eval_chars: !!python/tuple ["Haohmaru", "Galford", "Nakoruru", "Tamtam", "Kusare"]

wrappers_settings:
  normalize_reward: true
  normalization_factor: 0.5
  no_attack_buttons_combinations: false
  stack_frames: 4
  dilation: 1
  add_last_action: false
  stack_actions: 1
  scale: true
  exclude_image_scaling: true
  role_relative: true
  flatten: true
  filter_keys: ["frame"]

policy_kwargs:
  #net_arch: [{ pi: [64, 64], vf: [32, 32] }]
  #net_arch: [64, 64]

ppo_settings:
  policy_type: "MultiInputPolicy"
  gamma: 0.94
  model_checkpoint: "0"
  learning_rate: [2.5e-4, 2.5e-6] # To start
  clip_range: [0.15, 0.025] # To start
  batch_size: 1024 #8 #nminibatches gave different batch size depending on the number of environments: batch_size = (n_steps * n_envs) // nminibatches
  n_epochs: 4
  n_steps: 128
  autosave_freq: 250_000
  time_steps: 500_000
  n_train_epochs: 4
  n_eval_episodes: 5

  gae_lambda: 0.95
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  normalize_advantage: false # Whether to normalize or not the advantage
  stats_window_size: 100 # Window size for the rollout logging, specifying the number of episodes to average the reported success rate, mean episode length, and mean reward over
  target_kl: null